version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  build:
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run fe:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            npm run fe:build
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      - run:
          name: Deploy frontend
          command: |
            npm run fe:deploy
      - run:
          name: Deploy backend
          command: |-
            aws s3 cp ./www/Archive.zip $S3_BUCKET_SERVER --profile default
            aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="Archive.zip" --profile default
            aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>> --profile default

workflows:
  build_and_deploy:
    jobs:
      - build
      
