version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  frontend:
    working_directory: ~/app
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Front-End Install
          command: npm run fe:install
      - run:
          name: Build Frontend
          command: npm run fe:build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: npm run fe:deploy
  backend:
    working_directory: ~/app
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Back-End Install
          command: |-
            npm run api:install
      - run:
          name: Build backend
          command: |-
            npm run api:build
      - aws-cli/install
      - run:
          name: Deploy backend
          command: |-
            -eb init udagram-api --platform node.js --region $AWS_REGION
            -eb create --sample udagram-api-dev
            -eb use udagram-api-dev
            -eb setenv  AWS_REGION=$AWS_REGION AWS_SECRET_ACCES_KEY=$AWS_SECRET_ACCES_KEY AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID POSTGRES_DB=$POSTGRES_DB POSTGRES_HOST=$POSTGRES_HOST POSTGRES_PASSWORD=$POSTGRES_PASSWORD DB_PORT=$DB_PORT POSTGRES_USERNAME=$POSTGRES_USERNAME PORT=$PORT
            -echo "deploy:
            artifact: www/Archive.zip" >> .elasticbeanstalk/config.yml
            
            -eb deploy udagram-api-dev
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - backend
