version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  frontend:
    working_directory: ~/app
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Front-End Install
          command: npm run fe:install
      - run:
          name: Build Frontend
          command: npm run fe:build
      - aws-cli/install
      
  backend:
    working_directory: ~/app
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Back-End Install
          command: |-
            npm run api:install
      - run:
          name: Build backend
          command: |-
            npm run api:build
      - aws-cli/install
      

workflows:
  build_and_deploy:
    jobs:
      - frontend
      - backend
