version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  frontend:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
  
  server:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: BuildServer
          command: |-
            npm run build
     
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
